import DetailViewPage from "./DetailViewPage";
import DetailViewEpisode from "./DetailViewEpisode";
import { Episode } from "../infrastructure/redux/detail/types";
export { default as HomePageView } from "./HomePageView";
export { default as DetailViewPage } from "./DetailViewPage";
export { default as DetailViewEpisode } from "./DetailViewEpisode";
export { default as Cabecera } from "./Cabecera";
export { default as SpinnerIcon } from "./SpinnerIcon";
export { default as ListViewPage } from "./ListViewPage";
export { default as PodcasterCardDetail } from "./PodcasterCardDetail";
export { default as Episodes } from "./Episodes";
